server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:keeptrynjoy/config-sample.git
          default-label: main
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIEQXBix7RZP4dzViejpOQObD7dL5S0NpjCYEXm42mCDPoAoGCCqGSM49
            AwEHoUQDQgAEOE9r//yf3U1EYrh2NpfJPBSXbc9M56wJ1uvKC4hYDVQb3JHvcx7S
            I0ycS21xxZACsEOJM9OgilIrd513GbainQ==
            -----END EC PRIVATE KEY-----
          passphrase: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAI bmlzdHAyNTYAAABBBDhPa//8n91NRGK4djaXyTwUl23PTOesCdbryguIWA1UG9yR73Me0iNMnEttccWQArBDiTPToIpSK3eddxm2op0= kimsungmin@kimsungminui-MacBookPro.local